### ISSUE TITLE
can construction elevation scale caption be placed so it reads from the right like the depth below land surface scale does?

### ISSUE THREAD

**Issue by 1djp** [llorzol/klamath_wells#3]

**Comment by llorzol** [comment]
Need to move this to well construction

**Comment by 1djp** [comment]
Done.

**Comment by 1djp** [comment]
transferred to well construction

**Comment by llorzol** [comment]
Done will commit and install on Monday

**Comment by 1djp** [comment]
[like]  Polette, Danial J reacted to your message:
________________________________
From: Leonard Orzol ***@***.***>
Sent: Saturday, May 18, 2024 8:44:55 PM
To: llorzol/klamath_wells ***@***.***>
Cc: Polette, Danial J ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [llorzol/klamath_wells] can construction elevation scale caption be placed so it reads from the right like the depth below land surface scale does? (Issue #3)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Done will commit and install on Monday
